version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
    networks:
      - backend-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Redirect MongoDB logs to a specific file
    command: ["mongod", "--logpath", "/var/log/mongodb/mongod.log"]

networks:
  backend-network:
    driver: bridge
